name: js_dependency analysis
on:
  workflow_dispatch:
  pull_request:

jobs:
  js_dependency:
    name: Export Mermaid by js_dependency
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
      - run: echo ${{ env.GIT_DIFF }}
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'
      - run: gem install js_dependency
      - name: Create report
        env:
          SRC_PATH: src
#          TARGET_PATHS: "${{ env.GIT_DIFF }}"
          CHILD_ANALYZE_LEVEL: 2
          PARENT_ANALYZE_LEVEL: 2
          NAME_LEVEL: 2
          ALIAS_PATHS: "@:./pages"
          IDENTIFIER: js_dependency_pull_request_comments_${{ github.ref }}
          EXCLUDE_OUTPUT_NAMES: "pages"
        run: |
          cat << EOF > ${{ github.sha }}_comment
          `js_dependency export_markdown_report -s ${SRC_PATH} -t ${{ env.GIT_DIFF }} -a ${ALIAS_PATHS} -c ${CHILD_ANALYZE_LEVEL} -p ${PARENT_ANALYZE_LEVEL} --identifier ${IDENTIFIER} --exclude-output-names ${EXCLUDE_OUTPUT_NAMES}`
          
          ### Analyzed commit
          ${{ github.sha }}
          EOF
      #        if: env.GIT_DIFF
      - id: get-comment-body
        run: |
          body="$(cat ${{ github.sha }}_comment)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      #        if: env.GIT_DIFF
      - name: Upsert JsDependency PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.get-comment-body.outputs.body }}
          comment_includes: "<!-- js_dependency_pull_request_comments_${{ github.ref }} -->"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        if: env.GIT_DIFF

