name: js_dependency analysis
on:
  workflow_dispatch:
  pull_request:

jobs:
  js_dependency:
    name: Export Mermaid by js_dependency
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'
      - run: gem install js_dependency
      - name: Create comments
        run: |
          cat << EOF > comments
          ## JsDependency Report

          ### Orphaned dependencies
          `js_dependency orphan -s src`
          
          ### Targeted dependencies
          \`\`\`mermaid
          `js_dependency -s src -t src/pages/app.js -a @:./pages -c 3 -p 3`
          \`\`\`
          
          ### Analyzed commit
          ${{ github.sha }}

          <!-- js_dependency_pull_request_comments_${{ github.ref }} -->
          EOF
      - id: get-comment-body
        run: |
          body="$(cat comments)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        env:
          URL: ${{ github.event.pull_request.html_url }}
        with:
          message: ${{ steps.get-comment-body.outputs.body }}
          comment_includes: "<!-- js_dependency_pull_request_comments_${{ github.ref }} -->"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
