name: js_dependency analysis
on:
  workflow_dispatch:
  pull_request:

jobs:
  js_dependency:
    name: Export Mermaid by js_dependency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
      - run: gem install js_dependency
      - run: js_dependency orphan -s src
