name: js_dependency analysis
on:
  workflow_dispatch:
  pull_request:

jobs:
  js_dependency:
    name: Export Mermaid by js_dependency
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
      - run: gem install js_dependency
      - run: js_dependency orphan -s src
      - run: gh --version
      - run: gh pr list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create comments
        run: |
          cat << EOF > comments
          1st
          ${{ github.event.pull_request.html_url }}
          3rd
          EOF
      - name: output orphaned dependencies
        run: |
          js_dependency orphan -s src >  comments
      - run: gh pr comment -F ./comments "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        env:
          URL: ${{ github.event.pull_request.html_url }}
        with:
          message: 'Content loaded ! (edited)Loading'
          comment_includes: 'Loading'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        env:
          URL: ${{ github.event.pull_request.html_url }}
        with:
          message: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
